### PR TITLE
Organized board positions properly

### PR DESCRIPTION
**Pull request by Koldenblue**
Git ignore file was updated.

Board was organized to have the positions and columns correspond to the x and y axes properly.

A dictionary of (board spaces 'a1'-'h8' : Piece object) was implemented.
There is already a dictionary of (board space 'a1' - 'h8' : Position object (x,y)).
Also a 2d array of board[8][8], where the values are piece objects.

The problem with these is that the Piece objects are not directly associated with Position objects - as demonstrated by the first two dictionaries. For the array, for example, board[0][0] is only indirectly associated with the object "Position(0, 0)". 

Maybe I need a dictionary of (Position object : Piece object) ?

### CODE REVIEW

**Comment by Koldenblue** [comment]
Also is the gitignore for pycache not working properly?

**Comment by Koldenblue** [comment]
> 
> 
> Also is the gitignore for pycache not working properly?
> 
> It looks like the new pycache files got uploaded. Also is there a way to delete the pycache folder from github? I could do "rm -r pycache" in git bash, but I'm afraid that will just delete it from my computer, rather than github.

So I figured out that deleting a folder on github (pycache or other more important files) will also delete it from my local repository. As far as I can figure, the way to get around this is just to back up locally, delete the github files, then restore my local files and make sure they are in .gitignore so that they don't get uploaded again.

**Comment by Koldenblue** [comment]
> 
> 
> Git ignore file was updated.
> 
> Board was organized to have the positions and columns correspond to the x and y axes properly.
> 
> A dictionary of (board spaces 'a1'-'h8' : Piece object) was implemented.
> There is already a dictionary of (board space 'a1' - 'h8' : Position object (x,y)).
> Also a 2d array of board[8][8], where the values are piece objects.
> 
> The problem with these is that the Piece objects are not directly associated with Position objects - as demonstrated by the first two dictionaries. For the array, for example, board[0][0] is only indirectly associated with the object "Position(0, 0)".
> 
> Maybe I need a dictionary of (Position object : Piece object) ?

Hmm but a dictionary of (Position object : Piece object) would result in me not being able to access the dictionary keys easily (because the keys would now be memory addresses of the Position objects).

So either the 2d array Board[8][8], storing Piece objects. Or a dictionary of the format (space 'a1' - 'h8' : Piece object.)

**Comment by tristanlmiller** [comment]
You can remove an object from the git repo without removing the local copy by using `git rm --cached`.

See https://stackoverflow.com/questions/7434449/why-use-git-rm-to-remove-a-file-instead-of-rm

**Comment by tristanlmiller** [comment]
.gitignore will prevent a file from being added to the repo, but doesn't remove it if it's already in the repo.

**Comment by Koldenblue** [comment]
Thanks Tristan!

Okay so I am still reorganizing the class files, I created a new branch for it. I'm figuring that the best way to organize classes is to start from the top (main.py) and move down to subclasses as needed. This way makes more sense, and avoids having class files circularly reference each other.

**Pull request merged**
